# Generated by Django 5.1.4 on 2024-12-17 14:16

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('place', models.CharField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='Last Login')),
                ('is_receiver', models.BooleanField()),
                ('is_donor', models.BooleanField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('acc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=50, null=True)),
                ('UPI_ID', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('expiry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gold', models.IntegerField(blank=True, default=0, null=True)),
                ('Silver', models.IntegerField(blank=True, default=0, null=True)),
                ('Cash', models.IntegerField(blank=True, default=0, null=True)),
                ('goods', models.IntegerField(blank=True, default=0, null=True)),
                ('AI', models.IntegerField(blank=True, default=0, null=True)),
                ('NI', models.IntegerField(blank=True, default=0, null=True)),
                ('tresure', models.IntegerField(blank=True, default=0, null=True)),
                ('zakath', models.FloatField(blank=True, default=0, null=True)),
                ('asset', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock_calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat', models.IntegerField(blank=True, default=0, null=True)),
                ('goat_zakath', models.CharField(blank=True, default=0, null=True)),
                ('camel', models.IntegerField(blank=True, default=0, null=True)),
                ('camel_zakath', models.CharField(blank=True, default=0, null=True)),
                ('cow', models.IntegerField(blank=True, default=0, null=True)),
                ('cow_zakath', models.CharField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
